### ISSUE TITLE
dht.findprovs() returns only the first entry

### ISSUE THREAD

**Issue by dbw9580** [ipfs/java-ipfs-http-client#109]
The IPFS daemon returns via the HTTP interface several JSON objects that are not embraced in a pair of square brackets, so JSONParser.parse terminates when it sees a full object from input and return that as its final answer. This results in only the first message being returned to client code, which often happens to be an "AddingPeer" or "SendingQuery" message. Such result is useless if the intention were to get a list of providers.

To be fair, what the daemon returns are not valid JSON, so I'm not sure whose bug this should be counted as.

**Comment by dbw9580** [comment]
Expected behavior: read all entries of messages, and filter out only [type 4 ("Provider")](https://github.com/libp2p/go-libp2p-routing/blob/c568217bd16dbdb16aaa3064f5d1f2dfa224b589/notifications/query.go#L22) messages.

**Comment by ianopolous** [comment]
Thanks for the bug report, this is fixed on master now. But without filtering the results.

**Comment by dbw9580** [comment]
I'm afraid the `findpeer` method also has the same bug. Possibly there are more.
