### ISSUE TITLE
Support for Ipfs on mobile devices

### ISSUE THREAD

**Issue by vasa-develop** [ipfs/java-ipfs-http-client#117]
I want to know about(asking with respect to the global scope of IPFS project. Not specific to this repo)

a) What is the current stage of support for Ipfs on mobile devices? Is it supported for both Android and Apple right now? Can I run a node on the mobile or for now we only have the APIs?

b) How feasible is to run an Ipfs node on a mobile device? Does it drains the battery too much when the node is run for a long time?

c) What is the priority of supporting Ipfs on mobile devices with respect to development on a scale from 1-10?

**Comment by ianopolous** [comment]
These are good questions, but out of scope for this repo. You can try asking on https://discuss.ipfs.io

**Comment by vasa-develop** [comment]
I actually [asked it there](https://discuss.ipfs.io/t/support-for-ipfs-on-mobile-devices/4311/2), but I didn't got any satisfactory response. So, I tried here:)
