### ISSUE TITLE
ipfs webui upload file directory failed

### ISSUE THREAD

**Issue by lwz5910** [ipfs/java-ipfs-http-client#122]
Failed to add files to IPFS. Please try again.
![1](https://user-images.githubusercontent.com/5524709/49433042-04393280-f7ec-11e8-8d80-ef80ec1aa9c6.png)

**Comment by lwz5910** [comment]
go-ipfs v0.4.18

**Comment by ianopolous** [comment]
Can you a file an issue on https://github.com/ipfs/go-ipfs ?
This repo is just the java client.
