### ISSUE TITLE
Feature Request: InputStreamWrapper as NamedStreamable

### ISSUE THREAD

**Issue by remmerw** [ipfs/java-ipfs-http-client#124]
Feature Request: InputStreamWrapper as NamedStreamable
would be very usefull (in some cases no transformation required)

Example:

class InputStreamWrapper implements NamedStreamable {
        private final Optional<String> name;
        private final InputStream stream;

        public InputStreamWrapper(InputStream stream) {
            this(Optional.empty(), stream);
        }

        public InputStreamWrapper(String name, InputStream stream) {
            this(Optional.of(name), stream);
        }

        public InputStreamWrapper(Optional<String> name, InputStream stream) {
            this.name = name;
            this.stream = stream;
        }

        public boolean isDirectory() {
            return false;
        }

        public InputStream getInputStream() {
            return stream;
        }

        @Override
        public List<NamedStreamable> getChildren() {
            return Collections.emptyList();
        }

        public Optional<String> getName() {
            return name;
        }
    }

**Comment by ianopolous** [comment]
I've just added this to master. Thanks for the suggestion.
