### ISSUE TITLE
Cannot create IPFS object on android device

### ISSUE THREAD

**Issue by redriel** [ipfs/java-ipfs-http-client#137]
When I try the command

`IPFS ipfs = new IPFS(new MultiAddress("/ip4/127.0.0.1/tcp/5001"));`

The app suddenly crashes. Do you have any suggestion?

**Comment by ianopolous** [comment]
Are you also running a local ipfs daemon?

**Comment by redriel** [comment]
Yes; I solved the problem surrounding the statement with try...catch

**Comment by kuabhish** [comment]
Hey @redriel  What is the solution for this. ?
