### ISSUE TITLE
Couldn't connect to IPFS daemon

### ISSUE THREAD

**Issue by redriel** [ipfs/java-ipfs-http-client#138]
Hi, I'm working on Android. I managed to instantiate an IPFS object like this:
```
Thread ipfsThread = new Thread(() -> {
       try{
	IPFS ipfs = new IPFS(new MultiAddress("/ip4/127.0.0.1/tcp/5001"));
	toastAsync("Connected to IPFS");
	} catch (Exception e ){
		e.printStackTrace();
	}
});
ipfsThread.start();
```

However, I get this error:
![error](https://user-images.githubusercontent.com/36071958/58078385-e51e3980-7bae-11e9-906f-deb19485f2cc.png)

I do indeed have a daemon running locally:
![daemon](https://user-images.githubusercontent.com/36071958/58078406-f6ffdc80-7bae-11e9-8780-2ee209cf7f18.png)

Am I getting something wrong?

**Comment by sontqq** [comment]
Have you found a solution to this? I'm stucked at getting the same error.

**Comment by redriel** [comment]
Unfortunately no, I had to give up the project. IRC the author said Android was not supported so I think library cannot work on Android.

**Comment by vsbogd** [comment]
@redriel, I used this library on Android successfully. If you get this issue on Android emulator then you should try using 10.0.2.2 instead of 127.0.0.1 to connect to host device. See [official documentation](https://developer.android.com/studio/run/emulator-networking).

**Comment by odisseus** [comment]
Can this issue be closed?
