### ISSUE TITLE
How to connetc other IPFS network？

### ISSUE THREAD

**Issue by sunalive2013** [ipfs/java-ipfs-http-client#98]
I have already set up a IPFS on a ubuntu clinent，I need to connet tothe ubuntu client through the IP "/ip4/192.168.20.234/tcp/5001". But it faild，the IPFS thred is exit。

**Comment by HongnianZhang** [comment]
I think you need to config your ubuntu ipfs. 
try this on your ubuntu client:
```shell
ipfs shutdown
ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
ipfs daemon &
```
